server:
    port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: api
          uri : http://localhost:8081/
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: api_login
          uri: http://localhost:8082/
          predicates:
            - Path=/api_login/**