version: "3.9"

services:
    mysql:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: jwtoken
            MYSQL_USER: mysql
            MYSQL_PASSWORD: root
        networks:
            - back

    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8001:80
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        networks:
            - back
    elasticsearch:
        container_name: viet-cinema-elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
        environment:
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - bootstrap.memory_lock=true
        ports:
            - 9200:9200
        volumes:
            - C:/data-es:/usr/share/elasticsearch/data
networks:
  back:
volumes:
  db_data: {}
